INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (1, 'Gldani', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (2, 'Didube', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (3, 'Vake', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (4, 'Isani', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (5, 'Krtsanisi', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (6, 'Mtatsminda', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (7, 'Nadzaladevi', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (8, 'Saburtalo', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (9, 'Samgori', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (10, 'Chugureti', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (11, 'Other', NULL, 0, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (12, 'Avchala', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (13, 'Bertubati', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (14, 'Gldani Massive', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (15, 'Gldanula', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (16, 'Zahesi', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (17, 'Upper Avchala', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (18, 'Koniaki district', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (19, 'Mukhiani', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (20, 'Mukhiani villas', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (21, 'Gldani', NULL, 1, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (22, 'Didube', NULL, 2, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (23, 'Digomi Massive', NULL, 2, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (24, 'Agaraki', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (25, 'Akhaldaba', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (26, 'Bagebi', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (27, 'Betania', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (28, 'Vake', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (29, 'Tkhinvali', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (30, 'Nearby Lisi Lake (Vake)', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (31, 'Nutsubidze micro-districts (I-V)', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (32, 'Students Settlement', NULL, 3, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (33, 'VIII. Legion Block', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (34, 'Avlabari', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (35, 'Elia', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (36, 'Vazisubani', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (37, 'Isani', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (38, 'Metekhi', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (39, 'Metromsheni', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (40, 'Navtlughi', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (41, '31st', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (42, 'Samgori', NULL, 4, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (43, 'Abanotubani', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (44, 'Betlemi Historic Quarter', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (45, 'Zemo Phonichala', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (46, 'Ortachala', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (47, 'Soghanlugi', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (48, 'Fonichala', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (49, 'Kvemo Ponichala', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (50, 'Kharpukhi', NULL, 5, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (51, 'Garetubani', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (52, 'Vera', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (53, 'Zemo Vera', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (54, 'Kveseti', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (55, 'Kojori', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (56, 'Krtsanisi', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (57, 'Mtatsminda', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (58, 'Okrokana', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (59, 'Samadlo', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (60, 'Sololaki', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (61, 'Tabakhmela', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (62, 'Fikris gora', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (63, 'Shindisi', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (64, 'Tsavkisi', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (65, 'Tsavkisi Valley', NULL, 6, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (66, 'Avshniani', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (67, 'Zghvisubani - Temka', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (68, 'Lotkini', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (69, 'Surrounding area of metro Guramishvili', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (70, 'Surrounding area of metro Grmaghele', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (71, 'Nadzaladevi', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (72, 'Sanzona', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (73, 'Feikrebi Settlement', NULL, 7, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (74, 'Didgori', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (75, 'Didi Digomi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (76, 'Dighmis Chala', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (77, 'Vazha-Pshavela Blocks', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (78, 'Vashlijvari', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (79, 'Vedzisi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (80, 'Tbilisi Diplomatic Village', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (81, 'Telovani', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (82, 'Lisi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (83, 'Nearby Lisi Lake (Saburtalo)', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (84, 'Saburtalo', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (85, 'Village Dighomi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (86, 'Kvemo Lisi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (87, 'Koshigora', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (88, 'Dzveli Vedzlisi', NULL, 8, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (89, 'Airport Settlement', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (90, 'Alexeevka', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (91, 'Africa', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (92, 'Dampalo', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (93, 'Didi Lilo', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (94, 'Varketili', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (95, 'Lilo District', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (96, 'Third Massive', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (97, 'Moscow Avenue', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (98, 'Navtlughi-2', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (99, 'Samgorski', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (100, 'Orkhevi', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (101, 'Patara Lilo', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (102, 'Samkhedro Kalaki', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (103, 'Saqnavtobi Dasakhleba', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (104, 'Sakhidroenergomsheni', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (105, 'Meurneoba Varketili', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (106, 'Tsinubani', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (107, 'Saint Barbare (ZMK)', NULL, 9, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (108, 'Vorontsovi', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (109, 'Ivertubani', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (110, 'Kukia', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (111, 'Okros ubani', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (112, 'Plekhanovi', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (113, 'Svanetis Ubani', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (114, 'Chugureti', NULL, 10, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (115, 'Giorgitsminda Settlement', NULL, 11, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (116, 'New city of Tbilisi sea', NULL, 11, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (117, 'Kalaubani', NULL, 11, 1);
INSERT INTO `districts`(`id`, `name`, `name_geo`, `parent_id`, `actived`) VALUES (118, 'Old Nadzaladevi', NULL, 11, 1);
